### ISSUE TITLE
proprietary-files.txt: No such file or directory

### ISSUE THREAD

**Issue by heriagape** [moonbutt74/device_samsung_a5ulte#1]
Hello,
I am really sorry, I dont know weather this is an issue.
I didn't have any other way to contact you.

everytime I am running **./extract-files.sh** I am getting the following errors

**grep: proprietary-files.txt: No such file or directory
wc: proprietary-files.txt: No such file or directory
grep: proprietary-files.txt: No such file or directory
grep: proprietary-files.txt: No such file or directory**

It is my first time trying to build CM. Is there any other thing that I should do so as the get the blob files from the phone?

Thank you in advance.

**Comment by moonbutt74** [comment]
hi, you need to have proprietary-files.txt in your device tree.
I don't own the device, so this was mostly cobbled together from other sources,

the proprietary-files.txt is basically a text list of needed/required prebuilt/proprietary binaries/libraries/xml configuration files, etc.,
so an example entry in that text would be
bin/toasty
vendor/lib/cheesey.yum_yum.so

so extract-files.sh would refer to that list [proprietary-files.text] and locate
/system/bin/toasty and /system/vendor/lib/cheesey.yum_yum.so
and created your vendor/<manufacturer>/<device> directory with those files in their appropriate place and correctly placed in product copy listing in the accompanying generated mk file[s]

**Comment by heriagape** [comment]
Thanks for the reply.
I have pulled the whole content of /system
How do I know the files to include, will I be correct by putting the path of every under *vendor/lib*, *lib* and *bin* having for extension .bin, .fw, .so

**Comment by moonbutt74** [comment]
okay, start with /system/vendor/lib
you likely need the following directories, drm egl mediadrm rfsa
in system/vendor/lib itself try and identify the libraries for qcom/qmi/qseecom , adreno files, thermal files, libtime_genoff libTimeservices, camera related files [libmm* , chromatix etc., drm libs , client libs

with system/lib you need the hw directory and for individual libraries you need to strings the libs from
/system/vendor/lib/ to find what dependencies actually are, jackpotclavin has a pretty good blob utility for doing that, check xda for aosp blob utility and here on github as well.

the commandline for strings-ing a file goes like this..., say you have a lib in system/vendor/lib/billy_the_lib.so .., run
strings billy_the_lib.so | grep "\.so"   ...., say it comes back with
sun_dance_lib.so
lib/sun_dance_lib.so
find sun_dance_lib.so and add the file by location to proprietary txt sans [system] so your entry would be
lib/sun_dance_lib.so
check other similar vendor source tree's for a good lead/idea on what you need

m

**Comment by heriagape** [comment]
Thanks a lot, I thing I managed to do so, here is the link to the file 
https://github.com/heriagape/android_device_samsung_a5lte/blob/master/proprietary-files.txt
my model is SM-A500F (a5lte) while your repo was for SM-A500FU (a5ulte)

But I haven't tried to build the ROM yet.
I'm not sure if I managed to build the CloclworkMod Recovery, here is my output I am getting at the end of the build.


----- Making recovery image ------
Copying baseline ramdisk...
Modifying ramdisk contents...
cp: cannot stat ‘/home/heri/android/system/out/target/product/a5lte/root/init.recovery.*.rc’: No such file or directory
build/core/Makefile:915: recipe for target '/home/heri/android/system/out/target/product/a5lte/ramdisk-recovery.img' failed
make: [/home/heri/android/system/out/target/product/a5lte/ramdisk-recovery.img] Error 1 (ignored)
/home/heri/android/system/out/target/product/a5lte/recovery.img maxsize=15949824 blocksize=135168 total=12673024 reserve=270336
Made recovery image: /home/heri/android/system/out/target/product/a5lte/recovery.img

\#\#\#\#\#\#\#\#\# make completed successfully (06:14 (mm:ss)) \#\#\#\#\#\#\#\#\#\#\#\#

**Comment by moonbutt74** [comment]
hi,
/home/heri/android/system/out/target/product/a5lte/recovery.img
that is your recovery.img
goto xda and look for instruction

m

**Comment by moonbutt74** [comment]
okay on proprietary files text, there are common android os files you should not be copying over as prebuilt, libc libc++ libm libz etc.,

compare your list to a similar device's to prine it down to what you actually need
